"""
ML Guardian — Incident Report Agent
Generates EU AI Act Article 62 compliant incident reports.
This is what makes the project stand out for European recruiters.
"""
import json
from datetime import datetime
from pathlib import Path
from jinja2 import Template

from core.state import GuardianState, AgentAction, SystemStatus
from config.settings import config
from utils.logger import get_logger
from utils.slack_notifier import notifier

logger = get_logger("incident_agent", agent="incident")

# EU AI Act Incident Report Template
INCIDENT_TEMPLATE = """
================================================================================
EU AI ACT — INCIDENT REPORT (Article 62)
================================================================================
Report ID:          {{ report_id }}
Generated:          {{ timestamp }}
System:             {{ system_name }}
Risk Category:      {{ risk_category }}
Organization:       {{ organization }}
Deployer Country:   {{ deployer_country }}
Annex III Category: {{ annex_iii_category }}
================================================================================

1. INCIDENT SUMMARY
-------------------
Type:               {{ incident_type }}
Severity:           {{ severity }}
Detection Method:   {{ detection_method }}
Detected At:        {{ detected_at }}

2. SYSTEM PERFORMANCE AT TIME OF INCIDENT
------------------------------------------
{% for metric, value in current_metrics.items() %}
{{ metric }}: {{ value }}
{% endfor %}

3. BASELINE PERFORMANCE (Reference)
------------------------------------
{% for metric, value in baseline_metrics.items() %}
{{ metric }}: {{ value }}
{% endfor %}

4. PERFORMANCE DEGRADATION
----------------------------
{% for metric, delta in degradation.items() %}
{{ metric }}: {{ delta }}
{% endfor %}

5. DRIFT ANALYSIS
-----------------
Dataset Drift Detected: {{ drift_detected }}
Drift Score:            {{ drift_score }}
Drifted Features:       {{ drifted_features|join(', ') }}
Total Features Checked: {{ total_features }}

6. ROOT CAUSE ANALYSIS
-----------------------
{{ root_cause }}

7. AFFECTED POPULATION
-----------------------
Estimated affected decisions: {{ affected_decisions }}
Time window:                  {{ time_window }}

8. MITIGATION ACTIONS TAKEN
-----------------------------
{% for action in mitigation_actions %}
- [{{ action.timestamp }}] {{ action.action }}: {{ action.details }}
{% endfor %}

9. CORRECTIVE MEASURES PLANNED
-------------------------------
{% for measure in corrective_measures %}
- {{ measure }}
{% endfor %}

10. COMPLIANCE STATUS
---------------------
Article 9  (Risk Management):     {{ compliance.risk_management }}
Article 14 (Human Oversight):     {{ compliance.human_oversight }}
Article 15 (Accuracy):            {{ compliance.accuracy }}
Article 62 (Incident Reporting):  {{ compliance.incident_reporting }}

11. AUDIT TRAIL
---------------
{% for entry in audit_trail %}
[{{ entry.timestamp }}] {{ entry.action }} — {{ entry.details }}
{% endfor %}

================================================================================
This report was auto-generated by ML Guardian.
EU AI Act reference: Regulation (EU) 2024/1689
================================================================================
"""


class IncidentAgent:
    """
    Generates EU AI Act compliant incident reports.
    
    Responsibilities:
        - Detect when incidents should be filed (Art. 62 triggers)
        - Generate structured incident reports
        - Save reports in JSONL for audit trail
        - Alert stakeholders via Slack
        - Track incident resolution
    """

    def __init__(self):
        self.eu_config = config.eu_ai_act

    def should_report(self, state: GuardianState) -> bool:
        """Check if an incident report should be generated."""
        if state.incident_active:
            return False

        # Trigger conditions (EU AI Act Article 62)
        triggers = []

        # 1. Critical drift detected
        if state.status == SystemStatus.CRITICAL:
            triggers.append("critical_drift")

        # 2. Performance below minimum threshold
        if state.drift_report and state.drift_report.performance_metrics:
            accuracy = state.drift_report.performance_metrics.get("accuracy", 1.0)
            if accuracy < 0.85:
                triggers.append("performance_below_minimum")

        # 3. Multiple consecutive drift detections
        recent_drifts = [
            a for a in state.action_log[-10:]
            if a.get("action") == "drift_check"
            and a.get("details", {}).get("drift_detected", False)
        ]
        if len(recent_drifts) >= 3:
            triggers.append("persistent_drift")

        return len(triggers) > 0

    def execute(self, state: GuardianState) -> GuardianState:
        """Generate an incident report."""
        if not self.should_report(state):
            return state

        logger.info("Incident agent triggered — generating EU AI Act report...")
        state.incident_active = True

        # Generate incident ID
        incident_id = f"INC-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}"
        state.incident_id = incident_id

        # Determine severity and root cause
        severity = "HIGH" if state.status == SystemStatus.CRITICAL else "MEDIUM"
        root_cause = self._analyze_root_cause(state)

        # Build report context
        drift_report = state.drift_report
        current_metrics = drift_report.performance_metrics if drift_report else {}
        baseline_metrics = state.champion_model.metrics if state.champion_model else {}

        degradation = {}
        for k in current_metrics:
            if k in baseline_metrics:
                delta = current_metrics[k] - baseline_metrics[k]
                degradation[k] = f"{delta:+.4f} ({delta / max(baseline_metrics[k], 0.001) * 100:+.1f}%)"

        context = {
            "report_id": incident_id,
            "timestamp": datetime.utcnow().isoformat(),
            "system_name": self.eu_config.system_name,
            "risk_category": self.eu_config.risk_category,
            "organization": self.eu_config.organization,
            "deployer_country": self.eu_config.deployer_country,
            "annex_iii_category": self.eu_config.annex_iii_category,
            "incident_type": "Model Performance Degradation",
            "severity": severity,
            "detection_method": "Automated drift monitoring (Evidently AI)",
            "detected_at": state.last_check,
            "current_metrics": current_metrics,
            "baseline_metrics": baseline_metrics,
            "degradation": degradation,
            "drift_detected": drift_report.dataset_drift if drift_report else False,
            "drift_score": f"{drift_report.drift_score:.4f}" if drift_report else "N/A",
            "drifted_features": drift_report.drifted_features if drift_report else [],
            "total_features": drift_report.total_features if drift_report else 0,
            "root_cause": root_cause,
            "affected_decisions": "Estimated based on production traffic volume",
            "time_window": f"{state.last_check} to present",
            "mitigation_actions": [
                {"timestamp": a["timestamp"], "action": a["action"],
                 "details": json.dumps(a.get("details", {}), default=str)}
                for a in state.action_log[-5:]
            ],
            "corrective_measures": [
                "Trigger automated model retraining with updated data",
                "Run A/B test to validate new model version",
                "Monitor post-retraining performance for 48 hours",
                "Update fairness audit with new production data",
                "Review and update drift detection thresholds if needed",
            ],
            "compliance": {
                "risk_management": "Active — continuous monitoring enabled",
                "human_oversight": "Active — Slack alerts to ML team",
                "accuracy": f"Under review — current accuracy: {current_metrics.get('accuracy', 'N/A')}",
                "incident_reporting": "Filed — this report",
            },
            "audit_trail": [
                {"timestamp": a["timestamp"], "action": a["action"],
                 "details": json.dumps(a.get("details", {}), default=str)[:100]}
                for a in state.action_log[-20:]
            ],
        }

        # Render report
        template = Template(INCIDENT_TEMPLATE)
        report_text = template.render(**context)

        # Save text report
        report_path = config.paths.reports / f"{incident_id}.txt"
        with open(report_path, "w") as f:
            f.write(report_text)

        # Save JSON version for programmatic access
        json_path = config.paths.reports / f"{incident_id}.json"
        with open(json_path, "w") as f:
            json.dump(context, f, indent=2, default=str)

        # Log audit entry
        state.log_action(
            AgentAction.INCIDENT_REPORTED,
            {
                "incident_id": incident_id,
                "severity": severity,
                "report_path": str(report_path),
                "root_cause": root_cause[:200],
            },
        )
        state.total_incidents += 1

        # Alert via Slack
        notifier.send_incident_alert(
            incident_id=incident_id,
            reason=root_cause[:200],
            metrics=current_metrics,
        )

        logger.info(f"Incident report generated: {report_path}")
        return state

    def _analyze_root_cause(self, state: GuardianState) -> str:
        """Analyze and describe the probable root cause."""
        causes = []

        if state.drift_report:
            dr = state.drift_report
            if dr.drift_score > 0.20:
                causes.append(
                    f"Significant data distribution shift detected "
                    f"(drift score: {dr.drift_score:.4f}). "
                    f"Affected features: {', '.join(dr.drifted_features[:5])}. "
                    f"This suggests the production data has diverged "
                    f"substantially from the training distribution."
                )
            if dr.performance_metrics:
                accuracy = dr.performance_metrics.get("accuracy", 1.0)
                if accuracy < 0.85:
                    causes.append(
                        f"Model accuracy dropped to {accuracy:.4f}, "
                        f"below the minimum threshold of 0.85. "
                        f"This likely indicates concept drift where the "
                        f"relationship between features and target has changed."
                    )

        if not causes:
            causes.append(
                "Multiple drift indicators triggered simultaneously. "
                "Further investigation required to determine specific root cause."
            )

        return " ".join(causes)

    def resolve_incident(self, state: GuardianState) -> GuardianState:
        """Mark the current incident as resolved."""
        if state.incident_active:
            state.incident_active = False
            state.log_action(
                AgentAction.INCIDENT_REPORTED,
                {"incident_id": state.incident_id, "status": "resolved"},
            )
            logger.info(f"Incident {state.incident_id} resolved.")
        return state
